// Single source of truth for customer FAQs: rendered on /faq (with JSON-LD)
// and fed to the AI assistant on design-request message threads so both give
// the same answers.
export type Faq = { q: string; a: string; link?: { href: string; label: string } };

export const FAQS: Faq[] = [
  { q: "How much does custom gear cost?", a: "Flat per-piece pricing with the custom design included: round-neck jerseys are $28 (any sport), V-necks $30, two-button $32, full-button $35, quarter-zips $40, pants and hoodies $40, shorts $25, embroidered hats start at $30, and socks are $15. Custom orders - including embroidered hats - start at 6 pieces per design. See the full list on our Pricing page. Prices are plus tax and shipping." },
  { q: "How do I place a team order?", a: "Head to Team Order, pick your jersey style, then either enter your roster yourself or share a link so each player adds their own name, number, and size. We email your total and a free design proof to approve before production." },
  { q: "Is there a minimum order?", a: "Custom orders start at 6 pieces per design - every design takes real mockup and production setup, so 6 is the floor on custom gear. That includes custom embroidered hats: 6 hats per design, embroidered in-house so they turn around fast." },
  { q: "How long does production take?", a: "Standard production is three weeks after final design approval, final roster submission, and deposit payment. Shipping time is additional. A confirmed $100 rush targets two weeks; shorter deadlines require a custom priority review. Specialty items may take longer." },
  { q: "How does sizing work?", a: "Our signature jerseys have a relaxed fit and run slightly large. Every product page has a size guide, and on team orders each player picks their own size to cut down on returns." },
  { q: "Do you really design for free?", a: "Yes, genuinely free. There's no design fee. Start a custom design, our in-house designer works up a mockup, and you see a proof and approve it with no commitment. You only pay when you place your order." },
  { q: "Can I customize name and number?", a: "Absolutely. Jerseys and apparel let you add a player name and number right on the product page, and team orders capture them per player." },
  { q: "Do you make custom embroidered hats?", a: "Yes - fitted Flexfit caps, snapbacks, and trucker hats embroidered with your logo. Standard hats start at $30, performance caps are $38, and an embroidered number on the back adds $5. The mockup is free; a one-time digitizing fee applies if we create the embroidery file (bring your own DST/EMB file and skip it). Hats are embroidered in-house, so smaller orders can turn around quickly when blanks are in stock.", link: { href: "/custom-hats", label: "See custom embroidered hats" } },
  { q: "Is there a minimum for custom hats?", a: "Custom embroidered hats start at 6 hats per design. The mockup is free; creating the stitch-ready embroidery file carries a one-time digitizing fee - or bring your own embroidery file (DST/EMB) and skip it. Standard fitted, snapback, and trucker hats are $30 each.", link: { href: "/custom-hats", label: "Custom embroidered hats" } },
  { q: "How much is a custom hype chain?", a: "The mockup is free - we design it to match your team's logo and colors so you can see it first. Producing the real 3D file is a one-time $50 charge per design, then each chain starts at $40 depending on how detailed the design and colors are. Order one for the dugout or a set for the whole roster.", link: { href: "/hype-chains", label: "See custom hype chains" } },
  { q: "How do I set up a team store?", a: "Reach out and we'll set up a branded store for your team so players and fans can order gear directly. Great for fundraisers and ongoing orders." },
  { q: "How do I check my orders, track my package, or see past orders?", a: "Go to your Order Portal and enter the email you ordered with - we'll send you a secure link, no password needed. Customer tracking appears there when the final shipment is headed to you, including a separate link for every package. After the final package is marked delivered, the portal shows the carrier-recorded delivery date and your seven-day problem-reporting deadline. Tracking from a designer, factory, or supplier to Slugger remains internal.", link: { href: "/portal", label: "Open your order portal" } },
  { q: "How does local pickup work?", a: "Select local pickup before the final invoice so no shipping is charged. We will contact you when the complete order is ready in Ocala. When staff hands it to you, we record the pickup time, email your confirmation, and display the seven-day inspection and problem-reporting deadline in your Order Portal.", link: { href: "/portal", label: "Open your order portal" } },
  { q: "Can I add more items to an order I already placed?", a: "Before payment, you can correct the roster and order details. A deposit or full payment locks those confirmed specifications for production. Later additions must be accepted as separately priced add-ons, may have added shipping, and can arrive on a different date. Open your Order Portal or contact us and we will confirm what is still possible.", link: { href: "/portal", label: "Open your order portal" } },
  { q: "Do I need an account or password to see my orders?", a: "No password needed. Just enter your email on the Order Portal and we send you a secure link to your orders. You can optionally set a password later if you'd like instant access next time.", link: { href: "/portal", label: "Open your order portal" } },
  { q: "Do you have a referral program?", a: "Yes. Every customer gets a personal referral link inside their Order Portal. Share it with another coach or team - when they place their first order, you both get a $25 credit toward your next Slugger order. There's no limit on how many teams you can refer.", link: { href: "/portal", label: "Get your referral link" } },
];
