// Single source of truth for customer FAQs: rendered on /faq (with JSON-LD)
// and fed to the AI assistant on design-request message threads so both give
// the same answers.
export type Faq = { q: string; a: string; link?: { href: string; label: string } };

export const FAQS: Faq[] = [
  { q: "How much does custom gear cost?", a: "Flat per-piece pricing with the custom design included: round-neck jerseys are $28 (any sport), two-button $32, full-button $35, quarter-zips $38, pants and hoodies $40, shorts $25, embroidered hats $25-30, socks $15. Custom orders - including embroidered hats - start at 6 pieces per design. See the full list on our Pricing page. Prices are plus tax." },
  { q: "How do I place a team order?", a: "Head to Team Order, pick your jersey style, then either enter your roster yourself or share a link so each player adds their own name, number, and size. We email your total and a free design proof to approve before production." },
  { q: "Is there a minimum order?", a: "Custom orders start at 6 pieces per design - every design takes real mockup and production setup, so 6 is the floor on custom gear. That includes custom embroidered hats: 6 hats per design, embroidered in-house so they turn around fast." },
  { q: "How long does production take?", a: "Most orders ship in 2-3 weeks after you approve your design. Need it sooner? Rush gets you there in about a week. Specialty items like hoodies, pants, or long-sleeve jerseys may add a few days." },
  { q: "How does sizing work?", a: "Our signature jerseys have a relaxed fit and run slightly large. Every product page has a size guide, and on team orders each player picks their own size to cut down on returns." },
  { q: "Do you really design for free?", a: "Yes, genuinely free. There's no design fee. Start a custom design, our in-house designer works up a mockup, and you see a proof and approve it with no commitment. You only pay when you place your order." },
  { q: "Can I customize name and number?", a: "Absolutely. Jerseys and apparel let you add a player name and number right on the product page, and team orders capture them per player." },
  { q: "Do you make custom embroidered hats?", a: "Yes - fitted Flexfit caps, snapbacks, and trucker hats embroidered with your logo. Snapbacks and truckers are $25, fitted hats are $30, and an embroidered number on the back adds $5. The mockup is free; a one-time digitizing fee applies if we create the embroidery file (bring your own DST/EMB file and skip it). Hats are embroidered in-house, so smaller orders turn around in just days.", link: { href: "/custom-hats", label: "See custom embroidered hats" } },
  { q: "Is there a minimum for custom hats?", a: "Custom embroidered hats start at 6 hats per design. The mockup is free; creating the stitch-ready embroidery file carries a one-time digitizing fee - or bring your own embroidery file (DST/EMB) and skip it. Same flat $25-30 per hat from 6 to 60.", link: { href: "/custom-hats", label: "Custom embroidered hats" } },
  { q: "How much is a custom hype chain?", a: "The mockup is free - we design it to match your team's logo and colors so you can see it first. Producing the real 3D file is a one-time $50 charge per design, then each chain starts at $40 depending on how detailed the design and colors are. Order one for the dugout or a set for the whole roster.", link: { href: "/hype-chains", label: "See custom hype chains" } },
  { q: "How do I set up a team store?", a: "Reach out and we'll set up a branded store for your team so players and fans can order gear directly. Great for fundraisers and ongoing orders." },
  { q: "How do I check my orders, track my package, or see past orders?", a: "Go to your Order Portal and enter the email you ordered with - we'll send you a secure link, no password needed. Customer tracking appears there only when the final package is headed to you. Tracking from a designer, factory, or supplier to Slugger is internal production tracking and is not shown in the customer portal. The link is just for you, so no one else can see your orders.", link: { href: "/portal", label: "Open your order portal" } },
  { q: "Can I add more items to an order I already placed?", a: "Yes, as long as it hasn't shipped yet. For a team-store order, open your Order Portal, find the order, and tap Add items - you pay only for the new pieces plus any shipping increase, and they go in the same box. For a coach's team order, the coach can add players right from their order link so the extras ship with the team.", link: { href: "/portal", label: "Open your order portal" } },
  { q: "Do I need an account or password to see my orders?", a: "No password needed. Just enter your email on the Order Portal and we send you a secure link to your orders. You can optionally set a password later if you'd like instant access next time.", link: { href: "/portal", label: "Open your order portal" } },
  { q: "Do you have a referral program?", a: "Yes. Every customer gets a personal referral link inside their Order Portal. Share it with another coach or team - when they place their first order, you both get a $25 credit toward your next Slugger order. There's no limit on how many teams you can refer.", link: { href: "/portal", label: "Get your referral link" } },
];
